"""Add smart_recommendations to RecommendationLog

Revision ID: 405b01ccad95
Revises: 51cc3fbfaca9
Create Date: 2026-03-27 15:10:49.468169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405b01ccad95'
down_revision: Union[str, Sequence[str], None] = '51cc3fbfaca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_logs', sa.Column('smart_recommendations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_logs', 'smart_recommendations')
    # ### end Alembic commands ###
