"""Add action_plan

Revision ID: b5019871e147
Revises: 51cc3fbfaca9
Create Date: 2026-03-26 15:47:04.451629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5019871e147'
down_revision: Union[str, Sequence[str], None] = '51cc3fbfaca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_logs', sa.Column('action_plan', sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_logs', 'action_plan')
    # ### end Alembic commands ###
